// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_comb_iterator
List cpp_comb_iterator(const Eigen::Map<Eigen::MatrixXd>& pmat, const Eigen::Map<Eigen::MatrixXd>& gmat, const Eigen::Map<Eigen::MatrixXd>& wmat, const IntegerMatrix& comb_matrix, int wcol, double const_factor, double PRE_constant);
RcppExport SEXP _selection_index_cpp_comb_iterator(SEXP pmatSEXP, SEXP gmatSEXP, SEXP wmatSEXP, SEXP comb_matrixSEXP, SEXP wcolSEXP, SEXP const_factorSEXP, SEXP PRE_constantSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type pmat(pmatSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type gmat(gmatSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type wmat(wmatSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type comb_matrix(comb_matrixSEXP);
    Rcpp::traits::input_parameter< int >::type wcol(wcolSEXP);
    Rcpp::traits::input_parameter< double >::type const_factor(const_factorSEXP);
    Rcpp::traits::input_parameter< double >::type PRE_constant(PRE_constantSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_comb_iterator(pmat, gmat, wmat, comb_matrix, wcol, const_factor, PRE_constant));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_selection_index_cpp_comb_iterator", (DL_FUNC) &_selection_index_cpp_comb_iterator, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_selection_index(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
