# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' C++ Iterator for Selection Index Combinations
#' 
#' Vectorized computation of selection indices for all trait combinations.
#' Replaces R loop with single-pass compiled code for massive speedup.
#' 
#' @param pmat Phenotypic variance-covariance matrix (n x n)
#' @param gmat Genotypic variance-covariance matrix (n x n)
#' @param wmat Weight vector (n x 1) or matrix (n x wcol)
#' @param comb_matrix Matrix of trait combinations (ncomb x ncomb_total)
#'   Each column is one combination (0-indexed trait indices)
#' @param wcol Weight column to use (0-indexed)
#' @param const_factor Constant factor (default: 2.063)
#' @param PRE_constant Constant for PRE calculation (default: 100 or 100/GAY)
#' 
#' @return List with:
#'   - IDs: Character vector of combination IDs
#'   - b_matrix: Matrix of b coefficients (ncomb_total x max_traits)
#'   - GAs: Numeric vector of genetic advances
#'   - PREs: Numeric vector of percent relative efficiencies
#' 
#' @keywords internal
cpp_comb_iterator <- function(pmat, gmat, wmat, comb_matrix, wcol = 0L, const_factor = 2.063, PRE_constant = 100.0) {
    .Call('_selection_index_cpp_comb_iterator', PACKAGE = 'selection.index', pmat, gmat, wmat, comb_matrix, wcol, const_factor, PRE_constant)
}

